alter table dev.items add column if not exists buy_price_atual integer check (buy_price_atual is null or buy_price_atual >= 0);
alter table dev.items add column if not exists sell_price integer not null default 0 check (sell_price >= 0);
comment on column dev.items.buy_price_atual is 'Preco de compra JA com desconto aplicado (ex: ball/potion -70%) -- o que o jogador realmente paga. Calculado por scripts/sync-item-prices-entry.ts a partir de src/data/items.ts, nao reimplementado em SQL.';
comment on column dev.items.sell_price is 'Preco de venda, calculado como buy_price_atual * SELL_ITEM_FRACTION. Mesma fonte do buy_price_atual.';

update dev.items set buy_price_atual = 60, sell_price = 30 where id = 'poke_ball';
update dev.items set buy_price_atual = 180, sell_price = 90 where id = 'great_ball';
update dev.items set buy_price_atual = 360, sell_price = 180 where id = 'ultra_ball';
update dev.items set buy_price_atual = 900, sell_price = 450 where id = 'premier_ball';
update dev.items set buy_price_atual = 90, sell_price = 45 where id = 'potion';
update dev.items set buy_price_atual = 210, sell_price = 105 where id = 'super_potion';
update dev.items set buy_price_atual = 360, sell_price = 180 where id = 'hyper_potion';
update dev.items set buy_price_atual = 750, sell_price = 375 where id = 'max_potion';
update dev.items set buy_price_atual = 1500, sell_price = 750 where id = 'revive';
update dev.items set buy_price_atual = 4000, sell_price = 2000 where id = 'max_revive';
update dev.items set buy_price_atual = 500, sell_price = 250 where id = 'old_rod';
update dev.items set buy_price_atual = 2000, sell_price = 1000 where id = 'good_rod';
update dev.items set buy_price_atual = 5000, sell_price = 2500 where id = 'super_rod';
update dev.items set buy_price_atual = null, sell_price = 500 where id = 'stone_normal';
update dev.items set buy_price_atual = null, sell_price = 500 where id = 'stone_fire';
update dev.items set buy_price_atual = null, sell_price = 500 where id = 'stone_water';
update dev.items set buy_price_atual = null, sell_price = 500 where id = 'stone_electric';
update dev.items set buy_price_atual = null, sell_price = 500 where id = 'stone_grass';
update dev.items set buy_price_atual = null, sell_price = 500 where id = 'stone_ice';
update dev.items set buy_price_atual = null, sell_price = 500 where id = 'stone_fighting';
update dev.items set buy_price_atual = null, sell_price = 500 where id = 'stone_poison';
update dev.items set buy_price_atual = null, sell_price = 500 where id = 'stone_ground';
update dev.items set buy_price_atual = null, sell_price = 500 where id = 'stone_flying';
update dev.items set buy_price_atual = null, sell_price = 500 where id = 'stone_psychic';
update dev.items set buy_price_atual = null, sell_price = 500 where id = 'stone_bug';
update dev.items set buy_price_atual = null, sell_price = 500 where id = 'stone_rock';
update dev.items set buy_price_atual = null, sell_price = 500 where id = 'stone_ghost';
update dev.items set buy_price_atual = null, sell_price = 500 where id = 'stone_dragon';
update dev.items set buy_price_atual = null, sell_price = 500 where id = 'stone_dark';
update dev.items set buy_price_atual = null, sell_price = 500 where id = 'stone_steel';
